### ISSUE TITLE
 learning time 

### ISSUE THREAD

**Issue by wada-s** [dhgrs/chainer-WaveGlow#1]
Hi!

I run the script with a single GPU, batch_size = 1 and iteration=1000000 but learning time will be 50 days.
How long have you been learning with the default parameters?

**Comment by dhgrs** [comment]
It took about 9.6 days with single 1080ti to train 500k iterations in my case (batch_size=2).
If it takes too long, please check GPU/CPU usage and disk I/O.
And I uploaded pretrained model. Please check README.
